### ISSUE TITLE
[@guanghechen/rollup-plugin-copy]: Homepage and Repository fields swapped

### ISSUE THREAD

**Issue by leumasme** [guanghechen/node-scaffolds#6]
[guanghechen/node-scaffolds/packages/rollup-plugin-copy/package.json](https://github.com/guanghechen/node-scaffolds/blob/main/packages/rollup-plugin-copy/package.json)
Repository leads to your profile repo, homepage leads to this repo. These two should be swapped. These fields are used for the "Homepage" and "Repository" links on the [npm page](https://www.npmjs.com/package/@guanghechen/rollup-plugin-copy)
Also, why are you always increasing the version of all packages in the monorepo, even if nothing changed? This causes a lot of update spam.

**Comment by guanghechen** [comment]
> Repository leads to your profile repo

Oh, yes. The link to the repository was filled incorrectly. Thank you for pointing it out. It will be fixed in the next release.

> homepage leads to this repo

I think the homepage url is correct, it should refer to the `@guanghechen/rollup-plugin-copy` readme, let me known if you have more convincing understanding.

> why are you always increasing the version of all packages in the monorepo, even if nothing changed

I hope to manage the packages in this monorepo using the same major version. You may have noticed that the documentation includes links with branch information. Whenever there are breaking changes in the packages being used, I will try to release a new branch. However, I do not have the resources to maintain all package branches and documentation. I apologize if this causes any inconvenience to you. Perhaps unsubscribing from email notifications for changes in this package would be a good idea. Alternatively, you can regularly check the CHANGELOG to see if there are any major changes to the packages you are interested in.

I appreciate that you're trying to use and provide suggestions for my open-source project code. However, as I mentioned, I'm not an expert in monorepos, and I need to ensure that all packages in this monorepo remain under one major version. I don't have a preference for minor version updates. If you have any solutions, I'm happy to try them out.

**Comment by leumasme** [comment]
> it should refer to the @guanghechen/rollup-plugin-copy readme

Ah, I see. I assumed the homepage was supposed to link to your profile Info repository, but this makes more sense.

I guess I will simply silence updates to packages from this repo until I need them.
Thank you for your work.
